export type Locale = "ru" | "en";

export const content = {
  ru: {
    nav: ["Проекты", "ИИ для бизнеса", "Обо мне", "Контакты"],
    build: "Обсудить проект",
    status: "Статус системы",
    operational: "Работает",
    heroTitle: "Создаю Системы Для Бизнеса",
    kicker: "ИИ. Автоматизация. Маркетинг.",
    intro: "Помогаю компаниям и основателям проектировать, создавать и масштабировать интеллектуальные системы, которые автоматизируют операции, увеличивают выручку и создают устойчивое преимущество.",
    explore: "Смотреть проекты",
    work: "Проблемы/Решение",
    working: "Сейчас в работе",
    news: "Лента новостей",
    allExperiments: "Все эксперименты",
    allNews: "Открыть ленту",
    featured: "Избранные проекты",
    projectsTitle: "Реальные продукты. Реальные системы.",
    allProjects: "Все проекты",
    business: "ИИ для бизнеса",
    businessTitle: "От проблем к интеллектуальным системам.",
    allSolutions: "Все решения",
    contactNumber: "07",
    contactTitle: "Давайте создадим",
    contactAccent: "то, что будет дальше.",
    contactText: "Я работаю с основателями и компаниями, создавая интеллектуальные системы, которые устраняют трение и дают рычаг роста.",
    contactNote: "Если у вас есть задача, которую стоит решить, давайте обсудим.",
    conversation: "Начать разговор",
    conversationText: "Расскажите о задаче или идее. Я отвечу в течение 1–2 рабочих дней.",
    name: "Ваше имя", email: "Email", type: "Тип запроса", message: "Расскажите о задаче", send: "Отправить сообщение", sending: "Отправка...",
    success: "Сообщение отправлено. Скоро свяжусь с вами.", error: "Не удалось отправить сообщение.",
    quote: "Я не предлагаю технологии ради технологий. Сначала разбираюсь, где бизнес теряет время, деньги и фокус, а потом создаю простую рабочую систему, которая помогает команде действовать быстрее и эффективнее.",
  },
  en: {
    nav: ["Projects", "AI For Business", "About", "Contact"],
    build: "Let’s Build",
    status: "System Status",
    operational: "Operational",
    heroTitle: "Building Systems For Real Impact.",
    kicker: "AI. Automation. Business Systems. Marketing.",
    intro: "I help businesses and founders design, build, and scale intelligent systems that automate operations, increase revenue, and create meaningful leverage.",
    explore: "Explore Projects",
    work: "Problems/Solutions",
    working: "Currently Working On",
    news: "Live News Feed",
    allExperiments: "View All Experiments",
    allNews: "View Full News Feed",
    featured: "Featured Projects",
    projectsTitle: "Real Products. Real Systems.",
    allProjects: "View All Projects",
    business: "AI For Business",
    businessTitle: "From Problems to Intelligent Systems.",
    allSolutions: "See All Solutions",
    contactNumber: "07",
    contactTitle: "Let’s Build",
    contactAccent: "What’s Next.",
    contactText: "I work with founders and businesses to build intelligent systems that remove friction and create leverage.",
    contactNote: "If you have a challenge worth solving, let’s talk.",
    conversation: "Start a Conversation",
    conversationText: "Tell me about your challenge or idea. I’ll get back within 1–2 business days.",
    name: "Your Name", email: "Email", type: "Request type", message: "Tell me about your challenge", send: "Send Message", sending: "Sending...",
    success: "Message sent. I’ll be in touch soon.", error: "Message could not be sent.",
    quote: "All you need to run a business is a phone.",
  },
} as const;

export const projects = [
  { number: "01", title: "BizTok", category: ["B2B видеоплатформа", "Live Commerce Platform"], image: "/projects/biztok/mainscreenbt.png" },
  { number: "02", title: "Virtual COO", category: ["Операционная AI-система", "AI Operating System"], image: "/projects/Virtual COO/main.png" },
  { number: "03", title: "Warehouse AI", category: ["Складская аналитика", "Inventory Intelligence"], image: "/projects/warehouse/main.png" },
  { number: "04", title: "Marketing Engine", category: ["Контент и автоматизация", "Content & Automation"], image: "/projects/n8n_news/main.jpg" },
  { number: "05", title: "Den Workspace", category: ["Персональная AI-экосистема", "Personal Lab & OS"], image: "/ai-universe/main-planet-v13.png" },
];

export const workItems = [["AI Automations", "In Progress"], ["Business Systems", "Testing"], ["AI Agents Ecosystem", "Building"], ["Robotics Integrations", "Research"]];
export const newsItems = [["New reasoning model for complex tasks", "2m"], ["Humanoid robot starts real-world trials", "15m"], ["AI agents move from demos to operations", "32m"], ["Robotics VLA connects vision and action", "1h"], ["Automation becomes infrastructure", "2h"]];

export const solutions = [
  { p: ["Пропущенные заявки", "Missed Leads"], pd: ["Клиенты звонят после рабочего дня или не получают ответа.", "Customers call after hours or send inquiries."], s: ["ИИ-рецепционист", "AI Receptionist"], sd: ["Отвечает на звонки, квалифицирует лиды и обновляет CRM.", "Answers calls, qualifies leads and updates CRM."], r: ["Ни одной упущенной возможности", "Never Miss An Opportunity"], rd: ["Каждая заявка фиксируется и мгновенно направляется в работу.", "Every lead is captured and routed instantly."], icons: ["phone", "audio", "chart"] },
  { p: ["Ручные операции", "Manual Operations"], pd: ["Команда тратит часы на повторяющиеся задачи.", "Teams waste hours on repetitive tasks."], s: ["Автоматизация процессов", "Workflow Automation"], sd: ["Связывает сервисы и выполняет процессы от начала до конца.", "Connects tools and executes processes end-to-end."], r: ["Больше времени для роста", "More Time For Growth"], rd: ["Команда концентрируется на работе высокой ценности.", "Your team focuses on high-value work."], icons: ["file", "workflow", "clock"] },
  { p: ["Разрозненные данные", "Fragmented Information"], pd: ["Информация хранится в разных системах без общей картины.", "Data lives in multiple tools without one clear view."], s: ["Слой бизнес-аналитики", "Business Intelligence Layer"], sd: ["Объединяет продажи, операции и финансы в реальном времени.", "Unifies sales, operations and finance in real time."], r: ["Понятные решения", "Clear Visibility"], rd: ["Видно, что происходит и где нужно действовать.", "See what is happening and decide with confidence."], icons: ["database", "pie", "eye"] },
  { p: ["Контентные узкие места", "Content Bottlenecks"], pd: ["Создание и публикация контента занимают слишком много времени.", "Creating and publishing content takes too much time."], s: ["ИИ-контент-система", "AI Content Engine"], sd: ["Исследует, пишет и публикует контент по всем каналам.", "Researches, writes and publishes across channels."], r: ["Сильнее бренд, шире охват", "Stronger Brand, More Reach"], rd: ["Стабильное присутствие и рост без дополнительной нагрузки.", "Consistent presence and growth without more workload."], icons: ["megaphone", "pen", "rocket"] },
];
